name: frekio_radio
description: A privacy-friendly, open-source Internet radio app focused on Turkey.
publish_to: "none"
version: 1.0.0+5

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audio_service: ^0.18.19
  audio_session: ^0.2.4
  just_audio: ^0.10.6
  in_app_review: ^2.0.12
  in_app_update: ^5.0.0
  package_info_plus: ^10.2.1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/alpware_logo.png
    - assets/logo.png
